import { NextRequest, NextResponse } from "next/server";
import puppeteer from "puppeteer";
import { loadImageAsBase64 } from "../../../utils/pdf/loadImageAsBase64";
import { calculateUnifiedHappinessScore } from "@/lib/services/unified-happiness-scoring";
import { getEssentialName } from "@/lib/essential-mappings";

// Force Node.js runtime (disable Edge runtime)
export const runtime = "nodejs";
async function generatePDFHTML(result: any, language: string) {
  // Force English - Arabic RTL logic commented out
  // const isRTL = language === "ar";
  const isRTL = false; // Always use LTR for English
  // Force English language (override parameter)
  language = "en";

  // Translation objects
  const categoryTranslations = {
    Meaning: { en: "Meaning", ar: "المعنى" },
    Delight: { en: "Delight", ar: "البهجة" },
    Freedom: { en: "Freedom", ar: "الحرية" },
    Engagement: { en: "Engagement", ar: "الانخراط" },
    Vitality: { en: "Vitality", ar: "الحيوية" },
  };

  const categoryDescriptions = {
    Meaning: {
      en: "Your sense of purpose, spiritual connection, and alignment with core values.",
      ar: "إحساسك بالهدف، والاتصال الروحي، والتوافق مع القيم الأساسية.",
    },
    Delight: {
      en: "Your capacity for joy, playfulness, creativity, and appreciation of beauty.",
      ar: "قدرتك على الفرح، واللعب، والإبداع، وتقدير الجمال.",
    },
    Freedom: {
      en: "Your sense of autonomy, self-expression, and control over your life direction.",
      ar: "إحساسك بالاستقلالية والتعبير عن الذات والسيطرة على مسار حياتك.",
    },
    Engagement: {
      en: "Your level of involvement, focus, and utilization of skills in meaningful activities.",
      ar: "مستوى مشاركتك وتركيزك واستخدام مهاراتك في أنشطة ذات مغزى.",
    },
    Vitality: {
      en: "Your physical and mental energy, health, resilience, and overall well-being.",
      ar: "طاقتك البدنية والعقلية وصحتك ومرونتك ورفاهيتك العامة.",
    },
  };

  const getText = (key: string) => {
    const texts: Record<string, { en: string; ar: string }> = {
      title: { en: "Your Happiness Profile", ar: "ملفك الشخصي للسعادة" },
      subtitle: {
        en: "Discover your unique character and happiness dimensions",
        ar: "اكتشف شخصيتك الفريدة وأبعاد السعادة الخاصة بك",
      },
      youAre: { en: "You are a", ar: "أنت" },
      characterDesc: { en: "Your Character Description", ar: "وصف شخصيتك" },
      overallScore: {
        en: "Overall Happiness Score",
        ar: "النتيجة الإجمالية للسعادة",
      },
      overallLevel: {
        en: "Overall Happiness Level",
        ar: "مستوى السعادة الإجمالي",
      },
      dimensionsOverview: {
        en: "Happiness Dimensions Overview",
        ar: "نظرة عامة على أبعاد السعادة",
      },
      detailedDimensions: {
        en: "Detailed Happiness Dimensions",
        ar: "أبعاد السعادة التفصيلية",
      },
      detailedCharacterDesc: {
        en: "Detailed Character Analysis",
        ar: "تحليل الشخصية التفصيلي",
      },
      continued: {
        en: "Continued",
        ar: "تابع",
      },
      footer: {
        en: "Generated by Mountain View Happiness Survey",
        ar: "تم إنشاؤه بواسطة استطلاع السعادة من ماونتن فيو",
      },
    };

    // Force English - Arabic language selection commented out
    // const lang = language as "en" | "ar";
    // return texts[key]?.[lang] || texts[key]?.en || key;
    return texts[key]?.en || key;
  };

  // Calculate unified scores first (needed for overall percentage)
  // Force English - Arabic language parameter commented out
  const unifiedScore = await calculateUnifiedHappinessScore(
    result.answers || [],
    // language as "en" | "ar"
    "en" as "en" | "ar"
  );

  // Use unified scores for overall percentage
  const overallPercentage = unifiedScore.overallPercentage;
  const totalScore = unifiedScore.totalScore;

  // Get essential names for display
  const essentialNames: Record<string, string> = {};
  if (result.essentialTotals) {
    // This would need to be fetched from the database in a real implementation
    // For now, we'll use placeholder names
    Object.keys(result.essentialTotals).forEach((key) => {
      const essentialId = key.replace("essential_", "");
      essentialNames[key] = `Essential ${essentialId}`;
    });
  }

  // Color mapping for categories (updated to match brand specifications)
  const getCategoryColor = (category: string) => {
    const colors: Record<string, string> = {
      Meaning: "#784C9F", // rgb(120, 76, 159)
      Engagement: "#4972B8", // rgb(73, 114, 184)
      Freedom: "#F67E52", // rgb(246, 126, 82)
      Vitality: "#71AD46", // rgb(113, 173, 70)
      Delight: "#FEC010", // rgb(254, 192, 16)
    };
    return colors[category] || "#6B7280";
  };

  // Get truth icon path
  const getTruthIcon = (category: string): string => {
    const iconMap: Record<string, string> = {
      Meaning: "/truths/meaning.png",
      Freedom: "/truths/freedom.png",
      Vitality: "/truths/vitality.png",
      Engagement: "/truths/engagement.png",
      Delight: "/truths/delight.png",
    };
    return iconMap[category] || "/truths/meaning.png";
  };

  // Get essentials icon path
  const getEssentialsIcon = (category: string): string => {
    const iconMap: Record<string, string> = {
      Meaning: "/essentials/meaning-essentials.png",
      Freedom: "/essentials/freedom-essentials.png",
      Vitality: "/essentials/vitality-essentials.png",
      Engagement: "/essentials/engagement-essentials.png",
      Delight: "/essentials/delight-essentials.png",
    };
    return iconMap[category] || "/essentials/meaning-essentials.png";
  };

  // Load avatar image as base64
  const avatarPath =
    result.character.avatarUrl || `/characters/${result.code}.png`;

  const avatarBase64 = await loadImageAsBase64(avatarPath);

  // Load all truth icons as base64
  const truthIconsBase64: Record<string, string | null> = {};
  const essentialsIconsBase64: Record<string, string | null> = {};
  const truthCategories = [
    "Meaning",
    "Freedom",
    "Vitality",
    "Engagement",
    "Delight",
  ];

  for (const category of truthCategories) {
    const iconPath = getTruthIcon(category);
    const iconBase64 = await loadImageAsBase64(iconPath);
    truthIconsBase64[category] = iconBase64;

    const essentialsPath = getEssentialsIcon(category);
    const essentialsBase64 = await loadImageAsBase64(essentialsPath);
    essentialsIconsBase64[category] = essentialsBase64;

  }

  // Generate chart bars HTML using unified scores
  // Layout: percentage above each bar (matching app's Recharts LabelList),
  // bar in middle, truth photo and name at bottom
  const chartHeight = 180; // Height of chart area

  const chartBarsHTML = unifiedScore.categoryPercentages
    .map((category) => {
      const percentage = category.value;
      const height = Math.max((percentage / 100) * 180, 8);
      const color = category.color;
      const categoryName =
        categoryTranslations[category.name as keyof typeof categoryTranslations]
          ?.en || category.name;
      // Force English - Arabic translation commented out
      // ]?.[language as "en" | "ar"] || category.name;
      const iconBase64 = truthIconsBase64[category.name];

      // FIXED label position: place all labels as if bar height were 60%
      // (do NOT vary label height based on each bar's percentage)
      const fixedPct = 60;
      const fixedHeight = Math.max((fixedPct / 100) * chartHeight, 8);
      const labelBottom = chartHeight - fixedHeight + 8;

      return `
        <div style="display: flex; flex-direction: column; align-items: center; flex: 1; margin: 0 0.25rem; position: relative; height: 12rem;">
          <!-- Percentage above each bar (app style) -->
          <div style="position: absolute; bottom: ${labelBottom}px; font-size: 1.125rem; font-weight: 800; color: #111827; white-space: nowrap;">
            ${percentage}%
          </div>
          <!-- Bar -->
          <div style="
            width: 100%;
            border-top-left-radius: 0.375rem;
            border-top-right-radius: 0.375rem;
            background-color: ${color};
            height: ${height}px;
            min-height: 20px;
            margin-top: auto;
          "></div>
          <!-- Truth photo and name at bottom -->
          <div style="margin-top: 0.5rem; text-align: center;">
            ${
              iconBase64
                ? `<img src="${iconBase64}" alt="${category.name}" style="width: 2.5rem; height: 2.5rem; object-fit: contain; display: block; margin: 0 auto;" />`
                : `<div style="width: 2.5rem; height: 2.5rem; background-color: ${color}; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; font-size: 0.75rem; margin: 0 auto;">${category.name.charAt(
                    0
                  )}</div>`
            }
            <div style="font-size: 0.875rem; font-weight: 500; color: #374151; margin-top: 0.25rem;">
              ${categoryName}
            </div>
          </div>
        </div>
      `;
    })
    .join("");

  // Log detailed description status
  if (result.character.detailedDescription) {

  } else {

  }

  // Split categories for multi-page layout
  // Page 2: First 2 categories (Meaning, Delight typically)
  // Page 3: Remaining 3 categories (Freedom, Engagement, Vitality)
  const firstTwoCategories = unifiedScore.categoryPercentages.slice(0, 5);
  // const remainingCategories = unifiedScore.categoryPercentages.slice();

  // Function to generate dimension HTML for a category
  const generateDimensionHTML = (category: any) => {
    const percentage = category.value;
    const color = category.color;
    const categoryName =
      categoryTranslations[category.name as keyof typeof categoryTranslations]
        ?.en || category.name;
    // Force English - Arabic translation commented out
    // ]?.[language as "en" | "ar"] || category.name;
    const description =
      categoryDescriptions[category.name as keyof typeof categoryDescriptions]
        ?.en || "";
    // Force English - Arabic description commented out
    // ]?.[language as "en" | "ar"] || "";

    // Generate subtype progress bars using unified scores
    const essentialsIconBase64 = essentialsIconsBase64[category.name];
    const subtypeHTML = (["A", "B", "C", "D"] as const)
      .map((subtype) => {
        const subtypePercentage =
          unifiedScore.subtypePercentages[category.name][subtype];

        // Get Essential name instead of Type A/B/C/D
        // Force English - Arabic language parameter commented out
        const subtypeLabel = getEssentialName(
          category.name,
          subtype,
          // language as "en" | "ar"
          "en" as "en" | "ar"
        );

        const essentialsImageHTML = essentialsIconBase64
          ? `<img src="${essentialsIconBase64}" alt="${category.name} essentials" style="width: 1.5rem; height: 1.5rem; object-fit: contain; flex-shrink: 0;" />`
          : "";

        // Force English layout - Arabic layout commented out
        // return language === "ar"
        //   ? `
        //     <div style="margin: 0.5rem 0 0.5rem 0; display: flex; align-items: center; gap: 0.75rem;">
        //       <span style="min-width: 2.5rem; font-size: 0.75rem; font-weight: 600; color: #111827;">
        //         ${subtypePercentage}%
        //       </span>
        //       <div style="flex: 1; height: 6px; background-color: #e5e7eb; border-radius: 3px; overflow: hidden;">
        //         <div style="width: ${subtypePercentage}%; height: 100%; background-color: ${color}; border-radius: 3px; transition: width 0.3s ease; margin-left: auto;"></div>
        //       </div>
        //       <div style="width: 10rem; font-size: 0.875rem; font-weight: 500; color: #374151; text-align: right;">
        //         ${subtypeLabel}:
        //       </div>
        //       ${essentialsImageHTML}
        //     </div>
        //     `
        //   : `
        return `
            <div style="margin: 0.5rem 0 0.5rem 2rem; display: flex; align-items: center; gap: 0.75rem;">
              ${essentialsImageHTML}
              <div style="width: 10rem; font-size: 0.875rem; font-weight: 500; color: #374151; text-align: left;">
                ${subtypeLabel}:
              </div>
              <div style="flex: 1; height: 6px; background-color: #e5e7eb; border-radius: 3px; overflow: hidden;">
                <div style="width: ${subtypePercentage}%; height: 100%; background-color: ${color}; border-radius: 3px; transition: width 0.3s ease;"></div>
              </div>
              <span style="min-width: 2.5rem; font-size: 0.75rem; font-weight: 600; color: #111827;">
                ${subtypePercentage}%
              </span>
            </div>
            `;
      })
      .join("");

    const iconBase64 = truthIconsBase64[category.name];

    return `
        <div class="dimension-item" style="margin-bottom: 2rem; page-break-inside: avoid;">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem;">
            <div style="display: flex; align-items: center; gap: 0.75rem;">
              ${
                iconBase64
                  ? `<img src="${iconBase64}" alt="${category.name}" style="width: 2rem; height: 2rem; object-fit: contain; display: block;" />`
                  : `<div style="width: 2rem; height: 2rem; background-color: ${color}; border-radius: 50%; display: flex; align-items: center; justify-content: center; color: white; font-weight: bold; font-size: 0.625rem;">${category.name.charAt(
                      0
                    )}</div>`
              }
              <span style="font-weight: 700; font-size: 1.125rem; color: ${color};">
                ${categoryName}
              </span>
            </div>
            <span style="font-size: 1.5rem; font-weight: 700; color: #111827;">
              ${percentage}%
            </span>
          </div>
          
          <!-- Main Category Progress Bar -->
          <div style="margin: 0.75rem 0 0.75rem 1.75rem;">
            <div style="
              width: 100%; 
              height: 8px; 
              background-color: #e5e7eb; 
              border-radius: 4px; 
              overflow: hidden;
            ">
              <div style="
                width: ${percentage}%; 
                height: 100%; 
                background-color: ${color}; 
                border-radius: 4px;
                transition: width 0.3s ease;
              "></div>
            </div>
          </div>
          
          <!-- Subtype Breakdown -->
          <div style="margin: 1rem 0 1rem 1.75rem;">
            ${subtypeHTML}
          </div>
          
          <!-- Essential Scores (if available) -->
          ${
            result.essentialTotals
              ? Object.entries(result.essentialTotals)
                  .filter(([key]) => {
                    // Only show essentials that belong to this category
                    // This is a simplified check - in a real implementation, you'd fetch the essential's category
                    return true; // For now, show all essentials
                  })
                  .map(([essentialKey, essentialScore]) => {
                    const essentialName =
                      essentialNames[essentialKey] ||
                      essentialKey.replace("essential_", "Essential ");
                    const essentialPercentage = Math.round(
                      ((essentialScore as number) / 5000) * 100
                    ); // Assuming max 5000 per essential

                    return `
                <div style="margin: 0.5rem 0 0.5rem 1.75rem; display: flex; align-items: center; gap: 0.75rem;">
                  <div style="min-width: 6rem; font-size: 0.875rem; font-weight: 500; color: #6b7280;">
                    🎯 ${essentialName}:
                  </div>
                  <div style="flex: 1; display: flex; align-items: center; gap: 0.5rem;">
                    <div style="
                      flex: 1;
                      height: 6px; 
                      background-color: #e5e7eb; 
                      border-radius: 3px; 
                      overflow: hidden;
                    ">
                      <div style="
                        width: ${essentialPercentage}%; 
                        height: 100%; 
                        background-color: ${color}; 
                        border-radius: 3px;
                        opacity: 0.7;
                      "></div>
                    </div>
                    <span style="min-width: 2.5rem; font-size: 0.75rem; font-weight: 600; color: #111827;">
                      ${essentialPercentage}%
                    </span>
                  </div>
                </div>
              `;
                  })
                  .join("")
              : ""
          }
          
          <p style="color: #4b5563; line-height: 1.625; margin-left: 1.75rem;">
            ${description}
          </p>
        </div>
      `;
  };

  // Generate HTML for first two categories (Page 2)
  const detailedDimensionsPage2HTML = firstTwoCategories
    .map(generateDimensionHTML)
    .join("");

  // Generate HTML for remaining categories (Page 3)
  // const detailedDimensionsPage3HTML = remainingCategories
  //   .map(generateDimensionHTML)
  //   .join("");

  return `
    <!DOCTYPE html>
    <html lang="en" dir="ltr">
    <!-- Force English - Arabic language/direction commented out -->
    <!-- <html lang="${language}" dir="${isRTL ? "rtl" : "ltr"}"> -->
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Happiness Survey Report - ${
          // Force English - Arabic name commented out
          // language === "ar" ? result.character.nameAr : result.character.nameEn
          result.character.nameEn
        }</title>
        
        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
        
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap');
        </style>

        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          
          body {
            background-color: #f9fafb;
            font-family: "Inter", sans-serif;
            /* Force English - Arabic font commented out */
            /* font-family: ${
              isRTL ? '"Cairo", sans-serif' : '"Inter", sans-serif'
            }; */
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          
          /* Enhanced page break control */
          .page-break-before { page-break-before: always; }
          .page-break-after { page-break-after: always; }
          .page-break-inside-avoid { page-break-inside: avoid; }
          
          /* Ensure sections don't break awkwardly */
          .character-section { page-break-inside: avoid; min-height: 200px; }
          .score-section { page-break-inside: avoid; min-height: 150px; }
          .chart-section { page-break-inside: avoid; min-height: 300px; }
          .detailed-section { page-break-inside: avoid; }
          .dimension-item { page-break-inside: avoid; margin-bottom: 2rem; }
          
          /* Group score and chart sections together like Arabic layout */
          .score-chart-group { page-break-inside: avoid; page-break-before: always; }
          
          /* Detailed description styling */
          .detailed-description-content h3 { 
            font-size: 1.25rem; 
            font-weight: 600; 
            color: #1f2937; 
            margin: 1.5rem 0 1rem 0; 
          }
          .detailed-description-content h4 { 
            font-size: 1.125rem; 
            font-weight: 600; 
            color: #374151; 
            margin: 1.25rem 0 0.75rem 0; 
          }
          .detailed-description-content p { 
            margin: 0.75rem 0; 
            line-height: 1.625; 
          }
          .detailed-description-content ul { 
            margin: 0.75rem 0; 
            padding-left: 1.5rem; 
          }
          .detailed-description-content li { 
            margin: 0.5rem 0; 
            line-height: 1.5; 
          }
          .detailed-description-content strong { 
            font-weight: 600; 
            color: #1f2937; 
          }
          
          @media print {
            .character-section { break-inside: avoid; }
            .score-section { break-inside: avoid; }
            .chart-section { break-inside: avoid; }
            .detailed-section { break-inside: avoid; }
            .dimension-item { break-inside: avoid; }
            
            /* Force page breaks before major sections if needed */
            .force-new-page { page-break-before: always; }
          }
        </style>
      </head>

      <body>
        <!-- ==================== PAGE 1: INTRODUCTION ==================== -->
        <div style="min-height: 100vh; padding: 2rem; max-width: 56rem; margin: 0 auto; background-color: white; page-break-after: always;">
          <!-- Header -->
          <div style="text-align: center; margin-bottom: 3rem;">
            <div style="margin-bottom: 1.5rem;">
              <span style="font-size: 1.875rem; font-weight: 700; color: #3b82f6;">Beyond</span>
              <span style="font-size: 1.875rem; font-weight: 700; color: #1f2937; margin-left: 0.5rem;">Happiness</span>
              <!-- Force English - Arabic RTL margin commented out -->
              <!-- <span style="font-size: 1.875rem; font-weight: 700; color: #1f2937; ${
                isRTL ? "margin-right" : "margin-left"
              }: 0.5rem;">Happiness</span> -->
            </div>
            <h1 style="font-size: 2.25rem; font-weight: 700; color: #2563eb; margin-bottom: 1rem;">
              ${getText("title")}
            </h1>
            <p style="font-size: 1.125rem; color: #4b5563;">${getText(
              "subtitle"
            )}</p>
          </div>

          <!-- Character Result -->
          <div style="text-align: center; margin-bottom: 2rem;">
            <div style="display: inline-block; padding: 1rem 2rem; background: linear-gradient(to right, #eff6ff, #faf5ff); border: 2px solid #bfdbfe; border-radius: 0.5rem; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);">
              <h2 style="font-size: 1.5rem; font-weight: 700; color: #2563eb;">
                ${getText("youAre")} ${
    // Force English - Arabic name commented out
    // language === "ar" ? result.character.nameAr : result.character.nameEn
    result.character.nameEn
  }!
              </h2>
            </div>
          </div>

          <!-- Character Avatar -->
          <div style="text-align: center; margin-bottom: 3rem;">
            ${
              avatarBase64
                ? `<img src="${avatarBase64}" 
                     alt="${
                       // Force English - Arabic name commented out
                       // language === "ar"
                       //   ? result.character.nameAr
                       //   : result.character.nameEn
                       result.character.nameEn
                     }" 
                     style="width: 20rem; height: 20rem; object-fit: contain; border-radius: 0.5rem;" />`
                : `<div style="
                   width: 12rem; 
                   height: 12rem; 
                   margin: 0 auto;
                   background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                   border-radius: 0.5rem;
                   display: flex;
                   align-items: center;
                   justify-content: center;
                   color: white;
                   font-size: 1.5rem;
                   font-weight: bold;
                 ">
                   ${result.character//   : result.character.nameEn //   ? result.character.nameAr // language === "ar" // Force English - Arabic name commented out
                   .nameEn
                     .charAt(0)
                     .toUpperCase()}
                 </div>`
            }
          </div>

          <!-- Overall Score -->
          <div style="background-color: white; border-radius: 0.5rem; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05); border: 1px solid #e5e7eb; padding: 2rem; text-align: center;">
            <h3 style="font-size: 1.5rem; font-weight: 700; color: #1f2937; margin-bottom: 1.5rem;">
              ${getText("overallScore")}
            </h3>
            <div style="margin-bottom: 1rem;">
              <span style="font-size: 3.75rem; font-weight: 700; color: #111827;">
                ${overallPercentage}%
              </span>
            </div>
            <p style="color: #4b5563;">${getText("overallLevel")}</p>
          </div>
        </div>

        <!-- ==================== PAGE 2: DIMENSIONS OVERVIEW + FIRST 2 CATEGORIES ==================== -->
        <div style="min-height: 100vh; padding: 2rem; max-width: 56rem; margin: 0 auto; background-color: white; page-break-after: always;">
          <!-- Dimensions Overview Chart -->
          <div style="margin-bottom: 3rem;">
            <h3 style="font-size: 1.5rem; font-weight: 700; color: #1f2937; margin-bottom: 2rem; text-align: center;">
              ${getText("dimensionsOverview")}
            </h3>

            <div style="background-color: #f9fafb; padding: 1.5rem; border-radius: 0.5rem;">
              <div style="display: flex; justify-content: space-between; align-items: flex-end; height: 12rem; margin-bottom: 1rem;">
                ${chartBarsHTML}
              </div>
            </div>
          </div>

          <!-- Detailed Dimensions - First 2 Categories -->
          <div style="background-color: white; border-radius: 0.5rem; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05); border: 1px solid #e5e7eb; padding: 2rem;">
            <h3 style="font-size: 1.5rem; font-weight: 700; color: #1f2937; margin-bottom: 2rem; text-align: center;">
              ${getText("detailedDimensions")}
            </h3>

            <div>
              ${detailedDimensionsPage2HTML}
            </div>
          </div>
        </div>

        <!-- ==================== PAGE 3: REMAINING 3 CATEGORIES ==================== -->
        
          </div>

        </div>

        ${
          result.character.detailedDescription
            ? `
        <!-- ==================== PAGE 4: DETAILED CHARACTER DESCRIPTION ==================== -->
        <div style="min-height: 100vh; padding: 2rem; max-width: 56rem; margin: 0 auto; background-color: white;">
          <div style="background-color: white; border-radius: 0.5rem; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05); border: 1px solid #e5e7eb; padding: 2rem;">
            <h3 style="font-size: 1.5rem; font-weight: 700; color: #1f2937; text-align: center; margin-bottom: 1.5rem;">
              ${getText("detailedCharacterDesc")}
            </h3>
            
            <div class="detailed-description-content" style="
              font-size: 1rem;
              line-height: 1.625;
              color: #374151;
              max-width: 48rem;
              margin: 0 auto;
              text-align: left;
              direction: ltr;
              /* Force English - Arabic RTL text alignment commented out */
              /* text-align: ${isRTL ? "right" : "left"};
              direction: ${isRTL ? "rtl" : "ltr"}; */
            ">
              ${result.character.detailedDescription}
            </div>
          </div>

          <!-- Footer -->
          <div style="margin-top: 3rem; text-align: center; color: #6b7280; font-size: 0.875rem;">
            
            <p style="margin-top: 0.5rem;">${new Date().toLocaleDateString()}</p>
          </div>
        </div>
        `
            : `
        <!-- Footer (No Page 4) -->
        <div style="margin-top: 3rem; text-align: center; color: #6b7280; font-size: 0.875rem;">
          
          <p style="margin-top: 0.5rem;">${new Date().toLocaleDateString()}</p>
        </div>
        `
        }
      </body>
    </html>
  `;
}

export async function POST(request: NextRequest) {

  try {
    const body = await request.json();

    const { result, lang = "en" } = body;
    const language = lang; // Use consistent variable name

    if (!result || !result.character || !result.categoryTotals) {
      return NextResponse.json(
        { error: "Missing result data" },
        { status: 400 }
      );
    }

    let browser;

    try {

      // Launch Puppeteer
      browser = await puppeteer.launch({
        headless: true,
        executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium',
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
          "--disable-accelerated-2d-canvas",
          "--no-first-run",
          "--no-zygote",
          "--single-process",
          "--disable-gpu",
          "--disable-web-security",
          "--disable-features=VizDisplayCompositor",
        ],
      });

      const page = await browser.newPage();

      // Set viewport for consistent rendering
      await page.setViewport({ width: 1200, height: 1600 });

      // Generate HTML content directly instead of navigating to a page

      const htmlContent = await generatePDFHTML(result, lang);

      // Set encoding to UTF-8 for Arabic support
      await page.setExtraHTTPHeaders({
        "Accept-Charset": "utf-8",
      });

      await page.setContent(htmlContent, {
        waitUntil: "networkidle0",
        timeout: 10000,
      });

      // Wait for fonts to load
      await page.evaluateHandle("document.fonts.ready");

      // Additional wait for rendering
      await new Promise((resolve) => setTimeout(resolve, 2000));

      // Generate PDF
      const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: {
          top: "0.5in",
          right: "0.5in",
          bottom: "0.5in",
          left: "0.5in",
        },
        preferCSSPageSize: true,
      });

      // Use character name from result data for filename (ASCII only)
      const characterName =
        language === "ar"
          ? result.character.nameAr
          : result.character.nameEn
              .replace(/[^\x00-\x7F]/g, "") // Remove non-ASCII characters
              .replace(/\s+/g, "_")
              .trim() || "Character";
      const filename = `${characterName}_Happiness_Report.pdf`;

      // Return PDF as response
      return new NextResponse(Buffer.from(pdfBuffer), {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${filename}"`,
          "Content-Length": pdfBuffer.length.toString(),
        },
      });
    } catch (error) {
      console.error("❌ PDF generation error:", error);

      return NextResponse.json(
        {
          error: "Failed to generate PDF",
          details: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 }
      );
    } finally {
      if (browser) {
        await browser.close();

      }
    }
  } catch (error) {
    console.error("❌ Request parsing error:", error);
    return NextResponse.json(
      { error: "Invalid request data" },
      { status: 400 }
    );
  }
}
