import { NextRequest, NextResponse } from "next/server";
import puppeteer from "puppeteer";
import { loadImageAsBase64 } from "../../../utils/pdf/loadImageAsBase64";
import { calculateSubtypeScores } from "@/lib/services/subtype-scoring";

// Force Node.js runtime (disable Edge runtime)
export const runtime = "nodejs";
async function generatePDFHTML(result: any, language: string) {
  const isRTL = language === "ar";

  // Translation objects
  const categoryTranslations = {
    Meaning: { en: "Meaning", ar: "المعنى" },
    Delight: { en: "Delight", ar: "البهجة" },
    Freedom: { en: "Freedom", ar: "الحرية" },
    Engagement: { en: "Engagement", ar: "الانخراط" },
    Vitality: { en: "Vitality", ar: "الحيوية" },
  };

  const categoryDescriptions = {
    Meaning: {
      en: "Your sense of purpose, spiritual connection, and alignment with core values.",
      ar: "إحساسك بالهدف، والاتصال الروحي، والتوافق مع القيم الأساسية.",
    },
    Delight: {
      en: "Your capacity for joy, playfulness, creativity, and appreciation of beauty.",
      ar: "قدرتك على الفرح، واللعب، والإبداع، وتقدير الجمال.",
    },
    Freedom: {
      en: "Your sense of autonomy, self-expression, and control over your life direction.",
      ar: "إحساسك بالاستقلالية والتعبير عن الذات والسيطرة على مسار حياتك.",
    },
    Engagement: {
      en: "Your level of involvement, focus, and utilization of skills in meaningful activities.",
      ar: "مستوى مشاركتك وتركيزك واستخدام مهاراتك في أنشطة ذات مغزى.",
    },
    Vitality: {
      en: "Your physical and mental energy, health, resilience, and overall well-being.",
      ar: "طاقتك البدنية والعقلية وصحتك ومرونتك ورفاهيتك العامة.",
    },
  };

  const getText = (key: string) => {
    const texts: Record<string, { en: string; ar: string }> = {
      title: { en: "Your Happiness Profile", ar: "ملفك الشخصي للسعادة" },
      subtitle: {
        en: "Discover your unique character and happiness dimensions",
        ar: "اكتشف شخصيتك الفريدة وأبعاد السعادة الخاصة بك",
      },
      youAre: { en: "You are a", ar: "أنت" },
      characterDesc: { en: "Your Character Description", ar: "وصف شخصيتك" },
      overallScore: {
        en: "Overall Happiness Score",
        ar: "النتيجة الإجمالية للسعادة",
      },
      overallLevel: {
        en: "Overall Happiness Level",
        ar: "مستوى السعادة الإجمالي",
      },
      dimensionsOverview: {
        en: "Happiness Dimensions Overview",
        ar: "نظرة عامة على أبعاد السعادة",
      },
      detailedDimensions: {
        en: "Detailed Happiness Dimensions",
        ar: "أبعاد السعادة التفصيلية",
      },
      footer: {
        en: "Generated by Mountain View Happiness Survey",
        ar: "تم إنشاؤه بواسطة استطلاع السعادة من ماونتن فيو",
      },
    };

    const lang = language as "en" | "ar";
    return texts[key]?.[lang] || texts[key]?.en || key;
  };

  // Calculate percentages
  const totalScore = Object.values(result.categoryTotals).reduce(
    (sum: number, score) => sum + (score as number),
    0
  );
  const maxPossibleScorePerCategory = 10000;
  const maxTotalScore = maxPossibleScorePerCategory * 5;
  const overallPercentage = Math.round((totalScore / maxTotalScore) * 100);

  // Get essential names for display
  const essentialNames: Record<string, string> = {};
  if (result.essentialTotals) {
    // This would need to be fetched from the database in a real implementation
    // For now, we'll use placeholder names
    Object.keys(result.essentialTotals).forEach((key) => {
      const essentialId = key.replace("essential_", "");
      essentialNames[key] = `Essential ${essentialId}`;
    });
  }

  // Color mapping for categories (updated to match brand specifications)
  const getCategoryColor = (category: string) => {
    const colors: Record<string, string> = {
      Meaning: "#7E57C2", // Purple rgb(126, 87, 194)
      Engagement: "#42A5F5", // Blue rgb(66, 165, 245)
      Freedom: "#FFA726", // Orange rgb(255, 167, 38)
      Vitality: "#66BB6A", // Green rgb(102, 187, 106)
      Delight: "#FFCA28", // Yellow/Amber rgb(255, 202, 40)
    };
    return colors[category] || "#6B7280";
  };

  // Load avatar image as base64
  const avatarPath =
    result.character.avatarUrl || `/characters/${result.code}.png`;
  const avatarBase64 = await loadImageAsBase64(avatarPath);

  console.log(`🖼️ Loading avatar: ${avatarPath}, success: ${!!avatarBase64}`);

  // Generate chart bars HTML
  const chartBarsHTML = Object.entries(result.categoryTotals)
    .map(([category, score]) => {
      const percentage = Math.round(
        ((score as number) / maxPossibleScorePerCategory) * 100
      );
      const height = Math.max((percentage / 100) * 180, 8);
      const color = getCategoryColor(category);
      const categoryName =
        categoryTranslations[category as keyof typeof categoryTranslations]?.[
          language as "en" | "ar"
        ] || category;

      return `
        <div style="display: flex; flex-direction: column; align-items: center; flex: 1; margin: 0 0.25rem;">
          <div style="
            width: 100%;
            border-top-left-radius: 0.375rem;
            border-top-right-radius: 0.375rem;
            display: flex;
            align-items: flex-end;
            justify-content: center;
            color: white;
            font-size: 0.875rem;
            font-weight: 600;
            background-color: ${color};
            height: ${height}px;
            min-height: 20px;
          ">
            ${percentage > 15 ? `${percentage}%` : ""}
          </div>
          <div style="margin-top: 0.5rem; text-align: center;">
            <div style="font-size: 0.875rem; font-weight: 500; color: #374151;">
              ${categoryName}
            </div>
            ${
              percentage <= 15
                ? `<div style="font-size: 0.75rem; color: #6b7280; margin-top: 0.25rem;">${percentage}%</div>`
                : ""
            }
          </div>
        </div>
      `;
    })
    .join("");

  // Calculate subtype scores using the imported service

  const subtypeScores = await calculateSubtypeScores(
    result.answers || [],
    result.categoryTotals
  );

  // Generate detailed dimensions HTML with subtypes
  const detailedDimensionsHTML = Object.entries(result.categoryTotals)
    .map(([category, score]) => {
      const percentage = Math.round(
        ((score as number) / maxPossibleScorePerCategory) * 100
      );
      const color = getCategoryColor(category);
      const categoryName =
        categoryTranslations[category as keyof typeof categoryTranslations]?.[
          language as "en" | "ar"
        ] || category;
      const description =
        categoryDescriptions[category as keyof typeof categoryDescriptions]?.[
          language as "en" | "ar"
        ] || "";

      // Generate subtype progress bars
      const subtypeHTML = ["A", "B", "C", "D"]
        .map((subtype) => {
          const subtypeScore = (subtypeScores[category] as any)[subtype];
          // Each subtype has 2 questions, each with max value of 2000, so max = 4000
          const subtypeMaxScore = 4000;
          const subtypePercentage = Math.round(
            (subtypeScore / subtypeMaxScore) * 100
          );

          const subtypeLabel =
            language === "ar" ? `النوع ${subtype}` : `Type ${subtype}`;

          return `
          <div style="margin: 0.5rem 0 0.5rem ${
            language === "ar" ? "0" : "2rem"
          }; display: flex; align-items: center; gap: 0.75rem;">
            <div style="min-width: 4rem; font-size: 0.875rem; font-weight: 500; color: #374151;">
              ${subtypeLabel}:
            </div>
            <div style="flex: 1; display: flex; align-items: center; gap: 0.5rem;">
              <div style="
                flex: 1;
                height: 6px; 
                background-color: #e5e7eb; 
                border-radius: 3px; 
                overflow: hidden;
              ">
                <div style="
                  width: ${subtypePercentage}%; 
                  height: 100%; 
                  background-color: ${color}; 
                  border-radius: 3px;
                  transition: width 0.3s ease;
                "></div>
              </div>
              <span style="min-width: 2.5rem; font-size: 0.75rem; font-weight: 600; color: #111827;">
                ${subtypePercentage}%
              </span>
            </div>
          </div>
        `;
        })
        .join("");

      return `
        <div class="dimension-item" style="margin-bottom: 2rem; page-break-inside: avoid;">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.75rem;">
            <div style="display: flex; align-items: center; gap: 0.75rem;">
              <div style="width: 1rem; height: 1rem; border-radius: 0.25rem; background-color: ${color};"></div>
              <span style="font-weight: 700; font-size: 1.125rem; color: ${color};">
                ${categoryName}
              </span>
            </div>
            <span style="font-size: 1.5rem; font-weight: 700; color: #111827;">
              ${percentage}%
            </span>
          </div>
          
          <!-- Main Category Progress Bar -->
          <div style="margin: 0.75rem 0 0.75rem 1.75rem;">
            <div style="
              width: 100%; 
              height: 8px; 
              background-color: #e5e7eb; 
              border-radius: 4px; 
              overflow: hidden;
            ">
              <div style="
                width: ${percentage}%; 
                height: 100%; 
                background-color: ${color}; 
                border-radius: 4px;
                transition: width 0.3s ease;
              "></div>
            </div>
          </div>
          
          <!-- Subtype Breakdown -->
          <div style="margin: 1rem 0 1rem 1.75rem;">
            ${subtypeHTML}
          </div>
          
          <!-- Essential Scores (if available) -->
          ${
            result.essentialTotals
              ? Object.entries(result.essentialTotals)
                  .filter(([key]) => {
                    // Only show essentials that belong to this category
                    // This is a simplified check - in a real implementation, you'd fetch the essential's category
                    return true; // For now, show all essentials
                  })
                  .map(([essentialKey, essentialScore]) => {
                    const essentialName =
                      essentialNames[essentialKey] ||
                      essentialKey.replace("essential_", "Essential ");
                    const essentialPercentage = Math.round(
                      ((essentialScore as number) / 5000) * 100
                    ); // Assuming max 5000 per essential

                    return `
                <div style="margin: 0.5rem 0 0.5rem 1.75rem; display: flex; align-items: center; gap: 0.75rem;">
                  <div style="min-width: 6rem; font-size: 0.875rem; font-weight: 500; color: #6b7280;">
                    🎯 ${essentialName}:
                  </div>
                  <div style="flex: 1; display: flex; align-items: center; gap: 0.5rem;">
                    <div style="
                      flex: 1;
                      height: 6px; 
                      background-color: #e5e7eb; 
                      border-radius: 3px; 
                      overflow: hidden;
                    ">
                      <div style="
                        width: ${essentialPercentage}%; 
                        height: 100%; 
                        background-color: ${color}; 
                        border-radius: 3px;
                        opacity: 0.7;
                      "></div>
                    </div>
                    <span style="min-width: 2.5rem; font-size: 0.75rem; font-weight: 600; color: #111827;">
                      ${essentialPercentage}%
                    </span>
                  </div>
                </div>
              `;
                  })
                  .join("")
              : ""
          }
          
          <p style="color: #4b5563; line-height: 1.625; margin-left: 1.75rem;">
            ${description}
          </p>
        </div>
      `;
    })
    .join("");

  return `
    <!DOCTYPE html>
    <html lang="${language}" dir="${isRTL ? "rtl" : "ltr"}">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Happiness Survey Report - ${result.character.name}</title>
        
        <!-- Google Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
        
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap');
        </style>

        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          
          body {
            background-color: #f9fafb;
            font-family: ${
              isRTL ? '"Cairo", sans-serif' : '"Inter", sans-serif'
            };
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          
          /* Enhanced page break control */
          .page-break-before { page-break-before: always; }
          .page-break-after { page-break-after: always; }
          .page-break-inside-avoid { page-break-inside: avoid; }
          
          /* Ensure sections don't break awkwardly */
          .character-section { page-break-inside: avoid; min-height: 200px; }
          .score-section { page-break-inside: avoid; min-height: 150px; }
          .chart-section { page-break-inside: avoid; min-height: 300px; }
          .detailed-section { page-break-inside: avoid; }
          .dimension-item { page-break-inside: avoid; margin-bottom: 2rem; }
          
          /* Group score and chart sections together like Arabic layout */
          .score-chart-group { page-break-inside: avoid; page-break-before: always; }
          
          @media print {
            .character-section { break-inside: avoid; }
            .score-section { break-inside: avoid; }
            .chart-section { break-inside: avoid; }
            .detailed-section { break-inside: avoid; }
            .dimension-item { break-inside: avoid; }
            
            /* Force page breaks before major sections if needed */
            .force-new-page { page-break-before: always; }
          }
        </style>
      </head>

      <body>
        <div style="min-height: 100vh; padding: 2rem; max-width: 56rem; margin: 0 auto; background-color: white;">
          <!-- Header -->
          <div style="text-align: center; margin-bottom: 3rem;">
            <div style="margin-bottom: 1.5rem;">
              <span style="font-size: 1.875rem; font-weight: 700; color: #3b82f6;">Beyond</span>
              <span style="font-size: 1.875rem; font-weight: 700; color: #1f2937; margin-left: 0.5rem;">Happiness</span>
            </div>
            <h1 style="font-size: 2.25rem; font-weight: 700; color: #2563eb; margin-bottom: 1rem;">
              ${getText("title")}
            </h1>
            <p style="font-size: 1.125rem; color: #4b5563;">${getText(
              "subtitle"
            )}</p>
          </div>

          <!-- Character Result -->
          <div style="text-align: center; margin-bottom: 2rem;">
            <div style="display: inline-block; padding: 1rem 2rem; background: linear-gradient(to right, #eff6ff, #faf5ff); border: 2px solid #bfdbfe; border-radius: 0.5rem; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05);">
              <h2 style="font-size: 1.5rem; font-weight: 700; color: #2563eb;">
                ${getText("youAre")} ${result.character.name}!
              </h2>
            </div>
          </div>

          <!-- Character Avatar -->
          <div style="text-align: center; margin-bottom: 2rem;">
            ${
              avatarBase64
                ? `<img src="${avatarBase64}" 
                     alt="${result.character.name}" 
                     style="width: 12rem; height: 12rem; object-fit: contain; border-radius: 0.5rem;" />`
                : `<div style="
                   width: 12rem; 
                   height: 12rem; 
                   margin: 0 auto;
                   background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                   border-radius: 0.5rem;
                   display: flex;
                   align-items: center;
                   justify-content: center;
                   color: white;
                   font-size: 1.5rem;
                   font-weight: bold;
                 ">
                   ${result.character.name.charAt(0).toUpperCase()}
                 </div>`
            }
          </div>

          <!-- Character Description -->
          <div class="character-section" style="text-align: center; margin-bottom: 3rem;">
            <h3 style="font-size: 1.25rem; font-weight: 700; color: #1f2937; margin-bottom: 1rem;">
              ${getText("characterDesc")}
            </h3>
            <p style="font-size: 1.125rem; color: #374151; line-height: 1.625; max-width: 48rem; margin: 0 auto;">
              ${result.character.description}
            </p>
          </div>

          <!-- Score + Chart Group (matching Arabic layout) -->
          <div class="score-chart-group">
            <!-- Overall Score -->
            <div class="score-section" style="background-color: white; border-radius: 0.5rem; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05); border: 1px solid #e5e7eb; padding: 2rem; margin-bottom: 3rem; text-align: center;">
              <h3 style="font-size: 1.5rem; font-weight: 700; color: #1f2937; margin-bottom: 1.5rem;">
                ${getText("overallScore")}
              </h3>
              <div style="margin-bottom: 1rem;">
                <span style="font-size: 3.75rem; font-weight: 700; color: #111827;">
                  ${overallPercentage}%
                </span>
              </div>
              <p style="color: #4b5563;">${getText("overallLevel")}</p>
            </div>

            <!-- Dimensions Overview -->
            <div class="chart-section" style="margin-bottom: 3rem;">
              <h3 style="font-size: 1.5rem; font-weight: 700; color: #1f2937; margin-bottom: 2rem; text-align: center;">
                ${getText("dimensionsOverview")}
              </h3>

              <div style="background-color: #f9fafb; padding: 1.5rem; border-radius: 0.5rem;">
                <div style="display: flex; justify-content: space-between; align-items: flex-end; height: 12rem; margin-bottom: 1rem;">
                  ${chartBarsHTML}
                </div>
              </div>
            </div>
          </div>

          <!-- Detailed Dimensions -->
          <div class="detailed-section" style="background-color: white; border-radius: 0.5rem; box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05); border: 1px solid #e5e7eb; padding: 2rem;">
            <h3 style="font-size: 1.5rem; font-weight: 700; color: #1f2937; margin-bottom: 2rem; text-align: center;">
              ${getText("detailedDimensions")}
            </h3>

            <div>
              ${detailedDimensionsHTML}
            </div>
          </div>

          <!-- Footer -->
          <div style="margin-top: 3rem; text-align: center; color: #6b7280; font-size: 0.875rem;">
            <p>${getText("footer")}</p>
            <p style="margin-top: 0.5rem;">${new Date().toLocaleDateString()}</p>
          </div>
        </div>
      </body>
    </html>
  `;
}

export async function POST(request: NextRequest) {
  console.log("🔥 NEW PDF API CALLED - Option 1 Implementation v2");
  try {
    const body = await request.json();
    console.log("📦 Received body:", JSON.stringify(body, null, 2));
    const { result, lang = "en" } = body;

    if (!result || !result.character || !result.categoryTotals) {
      return NextResponse.json(
        { error: "Missing result data" },
        { status: 400 }
      );
    }

    let browser;

    try {
      console.log(
        "🚀 Starting PDF generation for character:",
        result.character.name
      );
      console.log("📊 Category totals:", result.categoryTotals);

      // Launch Puppeteer
      browser = await puppeteer.launch({
        headless: true,
        args: [
          "--no-sandbox",
          "--disable-setuid-sandbox",
          "--disable-dev-shm-usage",
          "--disable-accelerated-2d-canvas",
          "--no-first-run",
          "--no-zygote",
          "--single-process",
          "--disable-gpu",
          "--disable-web-security",
          "--disable-features=VizDisplayCompositor",
        ],
      });

      const page = await browser.newPage();

      // Set viewport for consistent rendering
      await page.setViewport({ width: 1200, height: 1600 });

      // Generate HTML content directly instead of navigating to a page
      console.log("📄 Generating HTML content directly");

      const htmlContent = await generatePDFHTML(result, lang);

      // Set encoding to UTF-8 for Arabic support
      await page.setExtraHTTPHeaders({
        "Accept-Charset": "utf-8",
      });

      await page.setContent(htmlContent, {
        waitUntil: "networkidle0",
        timeout: 10000,
      });

      console.log("✅ HTML content set successfully");

      // Wait for fonts to load
      await page.evaluateHandle("document.fonts.ready");

      // Additional wait for rendering
      await new Promise((resolve) => setTimeout(resolve, 2000));

      console.log("🎨 Generating PDF...");

      // Generate PDF
      const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: {
          top: "0.5in",
          right: "0.5in",
          bottom: "0.5in",
          left: "0.5in",
        },
        preferCSSPageSize: true,
      });

      console.log("✅ PDF generated successfully");

      // Use character name from result data for filename (ASCII only)
      const characterName =
        result.character.name
          .replace(/[^\x00-\x7F]/g, "") // Remove non-ASCII characters
          .replace(/\s+/g, "_")
          .trim() || "Character";
      const filename = `${characterName}_Happiness_Report.pdf`;

      // Return PDF as response
      return new NextResponse(Buffer.from(pdfBuffer), {
        headers: {
          "Content-Type": "application/pdf",
          "Content-Disposition": `attachment; filename="${filename}"`,
          "Content-Length": pdfBuffer.length.toString(),
        },
      });
    } catch (error) {
      console.error("❌ PDF generation error:", error);

      return NextResponse.json(
        {
          error: "Failed to generate PDF",
          details: error instanceof Error ? error.message : "Unknown error",
        },
        { status: 500 }
      );
    } finally {
      if (browser) {
        await browser.close();
        console.log("🔒 Browser closed");
      }
    }
  } catch (error) {
    console.error("❌ Request parsing error:", error);
    return NextResponse.json(
      { error: "Invalid request data" },
      { status: 400 }
    );
  }
}
